### ISSUE TITLE
开始配置时，若传入无效错误的数据库地址，无明确提示

### ISSUE THREAD

**Issue by jianzhi2010** [callmewhy/PleaseBaoMe#1]
在配置时：

```
[PBMTool setDBFilePath:writableDBPath]
```

1，若传入writableDBPath地址非法，无明确提示，log显示：error opening，没给出明确提示；
2，若初入地址有效，但该目录下无此sqlite，FMDB为你自动生成sqlite，这个容易造成误解，令人困惑啊。

建议log给出明确提示，不知汪大大，意下如何呢？

**Comment by callmewhy** [comment]
有理：）晚上有空更新一下

**Comment by callmewhy** [comment]
https://github.com/callmewhy/PleaseBaoMe/commit/6c8b03d62797b574bf14d6c0c1c750a892232090 这样解决你的问题了吗

**Comment by jianzhi2010** [comment]
ok了，😄
